org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError
# Kuikly 2.24.0 在 CocoaPods 构建阶段仍会注册 Gradle Listener。
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

kotlin.code.style=official
kotlin.build.report.output=file
networkVersion=0.1.0-SNAPSHOT
